# Makefile.dep created Fri Jul 17 12:34:48 CEST 2015
bigint.o: bigint.cpp bigint.h debug.h relops.h ubigint.h
ubigint.o: ubigint.cpp ubigint.h debug.h relops.h general.h
libfns.o: libfns.cpp libfns.h bigint.h debug.h relops.h ubigint.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h general.h
general.o: general.cpp general.h debug.h
main.o: main.cpp bigint.h debug.h relops.h ubigint.h general.h \
 iterstack.h libfns.h scanner.h
